# (PART) 第一部分 总结 {-}

# 枚举法求概率 {#Summary01}

总体来看，有三种基本运算：幂方运算、排列运算、组合运算。

幂方运算适用于各次完全相同的重复事件，例如放回地取球并记录结果；组合运算适用于不考虑顺序的情况；排列运算适用于需要考虑顺序的情况。

需要注意的是，这里所谓的“完全相同的重复”、“不考虑顺序”、“考虑顺序”是**实质上而非文本上的**。而有时候我们需要把一个复杂过程分成几个简单过程，每一个过程中都可能面临这三种基本运算。下面举一些具体的例子。

**例一** 有$k$个坛子，每一个装有$n$个球，分别编号$1$至$n$，现在从每个坛子中任取一球，问$m$是所取的球中的最大编号的概率。（课本习题一第四题）

**分析：**

::: {.rmdnote}

由于每一次取球时面临的都是完全相同的坛子和完全相同的球，因而可以看作是简单的、互不影响的重复事件，用幂方运算可得一共有$n^k$种取法。而当$m$是所取得的球中编号最大的一个时有$m^k-(m-1)^k$种。从而得到概率。

:::

**例二** 一个孩子有12块形状相同的积木，其中6块黑色，4块红色，1块白色和1块蓝色。孩子想把这些积木排成一排，一共有多少排法？

**分析：**

::: {.rmdnote}

**法一：排列的思想**

假设各个方块都是不同的，那么很显然有$A_{12}^{12}$种排法。注意到积木形状是相同的，那么各颜色之间的顺序则是无关紧要的。[黑方块被重复排列了$A_6^6$次，红方块被重复排列了$A_4^4$次，白色和蓝色方块被重复排列了$A_1^1$次。]从而排法种数为：

$$\frac{A_{12}^{12}}{A_6^6A_4^4A_1^1A_1^1}=27720$$

**法二：组合的思想**

因为方块形状是相同的，因而同色方块之间的顺序就不构成差异了。那么实质上我们可以把“排列”过程理解成在12个位置中选出6个黑色的位置、4个红色的位置、1个白色的位置和1个蓝色的位置，即把该过程看成一个组合过程。从而一共有$C_{12}^6C_6^4C_2^1C_1^1=27720$种。

:::

注意到，在某些时候，题目会有一些限定，例如存在某两个（或多个）相互绑定的元素、某两个（或多个）相互冲突的元素。这时候，对绑定的情况，只需要将绑定的元素先视作一个元素进行外部的排列组合，再进行内部的排列组合；对冲突的情况，只需要先内部选择再加入外部即可。下面是一道例题。

**例三** 某人有8个朋友，他打算邀请其中5人参加聚会，若：

（1）如果有两人长期不和，不能同时参加聚会，他有多少种邀请方案？

（2）如果有某两人只能同时被邀请，一共有多少种邀请方案？

**分析：**

::: {.rmdnote}
（1）**法一：“元素冲突”的想法**

不妨给此二人编号1、2，则有三种情况：1被邀请；2被邀请；1、2皆未被邀请。那么一共有$C_6^5+C_2^1C_6^4=36$种。

**法二：“元素绑定”的想法**

不妨在所有可能性中减去二人同时被邀请的情况。那么一共有$C_8^5-C_2^2C_6^3=36$种。

（2）见于（1） 中法二。

:::

