# 样本空间与事件空间的一致性 {#Summary02}

在古典概型的问题中，样本空间与事件空间的一致性是十分重要的。当然在大多数情况下，我们能够自然地维持两者的一致，但在某些时候，可能会不自觉地走向错谬，例如下题：

**例一** 将$n$个球放入$N$个盒子中($n\le N$)，求每个盒子最多放一球的概率。

**分析：**

> （1）在没有任何限制的条件下，每一次放球都是一个完全一致的重复过程，很轻易我们就能给出放球的所有可能情况有$N^n$种。接着，我们很可能就开始想：每个盒子最多放一个球，那么只需要在$N$个盒子中选取出$n$个盒子，然后把组合数$C_N^n$除以$N^n$就能得到概率。<br><br>
但恰恰在第二步，我们出错了。$N^n$种的放法默认了球的异质性（或者说放球是有顺序的）和盒子的异质性。而在第二步中，我们又忽略了球的异质性，只考虑了盒子的异质性。这就造成了样本空间和事件空间的不相匹配。<br><br>
在我们选取了之前的样本空间的情况下，我们应该这样考虑第二步：第1个球有$N$个选择，第2个球有N-1个选择[因为第1个球所在的盒子已经不能放了]……直到第$n$个有$N-n$个选择。因此，事件空间的样本点数实际上是$A_N^n$而不是$C_N^n$[从数字关系上也可以看出：$\prod_{i=N-n}^{N}i=A_N^n$]。<br><br>
记事件$A=$“每个盒子最多放一球”。<br>
$$P\left(A\right)=\frac{A_N^n}{N^n}$$
（2）若我们正向考虑，那么题设事件是下列事件的和：有1个球、有2个球、有3个球、……有n个球。这显然并不好计算。我们不妨先求其对立事件，即有0个球的概率，再利用对立事件的性质和概率的公理求得题设事件的概率。<br><br>
计算对应样本空间的事件空间的样本点数时，我们可以将这个盒子无视，那么在考虑顺序和盒子异质性的情况下，就会有${(N-1)}^n$种可能。<br><br>
记事件$B=$“某指定的盒子不空”。<br>
$$P\left(B\right)=1-P\left(\bar{B}\right)=1-\frac{{(N-1)}^n}{N^n}$$

> **补充**：为什么要在这里假定放球有顺序、盒子不同？我们不妨做以下尝试。<br><br>
其一，若假定不考虑放球顺序，盒子不同，那么我们首先要确定不同的组合情况（例如某个盒子1个球、另一个盒子$n-1$个球，或$n$个盒子各1个，等等），其次要对每一种情况作排列计算（即选定哪个盒子放多少个）。这将是无比繁琐乃至于难以计算的，更何况在这种方式下选出的样本空间的样本点是不等可能的。<br><br>
其二，若假定不考虑放球顺序，且盒子相同，那么我们要做的就是确定不同的组合情况（例如某个盒子1个球、另一个盒子$n-1$个球，或$n$个盒子各1个，等等），即上面假设的第一步。但这仍然是难以计算的，同时，选出的样本空间的样本点亦不是等可能的。<br><br>
我们可以选取$N=2$，$n=2$的情况，计算在第一种假设下样本空间的不同样本点的各自的概率：<br><br>
记录每个盒子里的球数，以点对表示：<br>
$$\mathrm{\Omega}=\{\left(1,1\right),\left(2,0\right),(0,2)\}$$
列表可得（表略，利用考虑顺序和异质性下的古典概型即可得到）：<br>
$$P\left(\left(1,1\right)\right)=\frac{1}{2}\neq\frac{1}{3}$$
$$P\left(\left(2,0\right)\right)=P\left(\left(0,2\right)\right)=\frac{1}{4}\neq\frac{1}{3}$$
我们可以选取$N=3$，$n=2$的情况[之所以不选取$N=2$，$n=2$的情况，是因为在该情况下，这一样本空间很不巧地做到了样本点的等可能性；但是也请注意，我们只需举出一个反例就已经足够了，相对于更普遍的情况，$N=2$，$n=2$时的等可能性只是特殊情况而已]，计算在第二种假设下样本空间的不同样本点的各自的概率：<br>
$$\mathrm{\Omega}=\{一个盒子两个球两个盒子没有球，两个盒子一个球一个盒子没有球\}$$
列表可得（表略，利用考虑顺序和异质性下的古典概型即可得到）：<br>
$$P(一个盒子两个球两个盒子没有球)=13≠12$$
$$P(两个盒子一个球一个盒子没有球)=23≠12$$
这里可能会产生疑惑：为什么在另两个假设下求样本点概率还在用其假设外的某种假设下的古典概型？原因很简单，因为我们知道这个古典概型是可行的，因此用它来验证。

如果把详细的解析列出来，想必读者亦是能够理解的。难点恐怕在于，如何自觉地发现这些易错之处。简单地说，是把握住“异质”。“异质”可以有很多种表现形式：类别、顺序、个体差异等等。当然，“异质”只有在我们考虑它的时候才是必要的，而在不考虑的时候则完全是多余的，可以忽视。下面举一个具体的例子：

**例二** 一袋中装有$m+n$个球，其中$m$个黑球，$n$个白球，现随机地从中每次取出一个球（不放回），求下列事件的概率：

（1）第$i$次取到的是白球；

（2）第$i$次才取到白球；

（3）前$i$次中能取到白球；

（4）前$i$次中恰好取到$l$个白球（$l\le\ i\le\ m+n$，$l\le\ n$）；

（5）到第$i$次为止才取到$l$个白球（$l\le\ i\le\ m+n$，$l\le\ n$）；

（6）取球直到剩下的球的颜色都相同为止，最后剩下的全是白球。

**分析：**

> 这里的异质性表现为：球的两类颜色、球被取出的顺序（为了方便计算，每个球都是“独特”的“标了号的”），球被取出的顺序可以分解成两步：一步是确定结构，第二步是在结构内排序，用排列组合公式可以直观表示为：$A_N^M=C_N^MA_M^M$（$M\le\ N$）。<br><br>
最简单的想法是：认为每一球都是不同的（编号），于是有$A_{m+n}^{m+n}$种取法。如果选择了这一样本空间，那么在后面的计算中我们一定要保证，每一次选取都是考虑了所有$m+n$个球的顺序的。<br><br>
依次将六个事件标记为$A_i$，其中$i=1,2,3,4,5,6$。<br><br>
（1）第$i$次取到的是白球，最朴素的想法就是，在$n$个白球中取出一个放在第$i$个位置，前$i-1$个位置随机排列。从而有：<br>
$$P\left(A_1\right)=\frac{C_n^1A_{m+n-1}^{m+n-1}}{A_{m+n}^{m+n}}=\frac{n\left(m+n-1\right)!}{\left(m+n\right)!}=\frac{1}{m+n}$$
当然，我们可以只考虑前i次结果，那么相应地，样本空间点数也会变为$A_{m+n}^i$。下面几问亦然。<br><br>
至于更简便的想法，这里就略过了。<br><br>
（2）第$i$次才取到白球，只需要前$i-1$次都是黑球即可。从而有：<br>
$$P\left(A_2\right)=\frac{C_n^1A_m^{i-1}A_{m+n-i}^{m+n-i}}{A_{m+n}^{m+n}}=\frac{nA_m^{i-1}\left(m+n-i\right)!}{\left(m+n\right)!}=\frac{nA_m^{i-1}}{A_{m+n}^i}$$
（3）前$i$次中能取到白球，可以算其对立事件：前$i$次中全取到黑球。从而有：<br>
$$P\left(A_3\right)=1-\frac{A_m^iA_{m+n-i}^{m+n-i}}{A_{m+n}^{m+n}}=1-\frac{A_m^i\left(m+n-i\right)!}{\left(m+n\right)!}=1-\frac{A_m^i}{A_{m+n}^i}$$
当然，在这里，我们可以不考虑顺序（因为在这一问中这是可操作的）。那么，所有可能操作就是从$m+n$个球中取出$i$个球，样本点数为$C_{m+n}^i$。从而有：<br>
$$P\left(A_3\right)=1-\frac{C_m^i}{C_{m+n}^i}$$
这一方法的运用在（4）中亦然。<br><br>
（4）前$i$次中恰好取到$l$个白球，首先要确认取球过程中白球所在的位置。从而有：<br>
$$P\left(A_4\right)=\frac{C_i^lA_n^lA_m^{i-l}A_{m+n-i}^{m+n-i}}{A_{m+n}^{m+n}}=\frac{C_i^lA_n^lA_m^{i-l}\left(m+n-i\right)!}{\left(m+n\right)!}=\frac{C_i^lA_n^lA_m^{i-l}}{A_{m+n}^i}$$
在不考虑顺序的情况下，所有可能操作就是从$m+n$个球中取出$i$个球的过程，样本点数为$C_{m+n}^i$。符合题意的过程就是从$n$个白球中取出$l$个，从$m$个黑球中取出$i-l$个的过程。从而有：<br>
$$P\left(A_4\right)=\frac{C_n^lC_m^{i-l}}{C_{m+n}^i}$$
（5）到第$i$次为止才取到$l$个白球，即考虑顺序地在前$i-1$次取到$l-1$个白球以及$i-l$个黑球，第$i$次再在剩下的$n-l+1$个白球中取一个。从而有：<br>
$$P\left(A_5\right)=\frac{C_{i-1}^{l-1}A_n^{l-1}A_m^{i-l}C_{n-l+1}^1A_{m+n-i}^{m+n-i}}{A_{m+n}^{m+n}}=\frac{C_{i-1}^{l-1}A_n^{l-1}A_m^{i-l}C_{n-l+1}^1\left(m+n-i\right)!}{\left(m+n\right)!}\\=\frac{C_{i-1}^{l-1}A_n^{l-1}A_m^{i-l}C_{n-l+1}^1}{A_{m+n}^i}$$
（6）取球直到剩下的球的颜色都相同为止，最后剩下的全是白球，等价于最后一个取到白球。令$i=m+n$，则由（1）知：
$$P\left(A_6\right)=\frac{n}{m+n}$$

读者应该发现了，“异质”在不同语境下有不同的需要被考虑的程度。例如在例二的（3）、（4）中，顺序可以被忽略，而只考虑结构；在（2）、（5）中，不考虑顺序可能就无法进行下去。关于这一点，例一的“补充”部分已经说得很清楚了。我们应当让一个过程变得易于计算、易于理解，但也要避免出现样本空间和事件空间相分离的情况。

如果读者害怕出错，那么大可以在写完之后，重新回顾每一个算式所表达的含义。易错点在于各元素是否参与了排序，还是仅仅被考虑了结构，甚或是被放在其他的考虑中。算式本身，只要足够明晰，是能够反映思考的。

